package DE.scripts.world.systems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.*;
import com.fs.starfarer.api.campaign.econ.MarketAPI;
import com.fs.starfarer.api.impl.campaign.ids.Conditions;
import com.fs.starfarer.api.impl.campaign.ids.Industries;
import com.fs.starfarer.api.impl.campaign.ids.Items;
import com.fs.starfarer.api.impl.campaign.ids.Submarkets;
import com.fs.starfarer.api.util.Misc;

import java.util.ArrayList;
import java.util.Arrays;

import static DE.scripts.Gen.addMarketplace;
import static DE.scripts.DE_ModPlugin.DEenablefortressmode;
import static DE.scripts.DE_ModPlugin.DEenablelitemode;


public class DE_Askonia {
    boolean isPAGSM = Global.getSettings().getModManager().isModEnabled("PAGSM");

    public void generate(SectorAPI sector) {
        StarSystemAPI system = sector.getStarSystem("Askonia");
        LocationAPI hyper = Global.getSector().getHyperspace();

        /*
         * addPlanet() parameters:
         * 1. Unique id for this planet (or null to have it be autogenerated)
         * 2. What the planet orbits (orbit is always circular)
         * 3. Name
         * 4. Planet type id in planets.json
         * 5. Starting angle in orbit, i.e. 0 = to the right of the star
         * 6. Planet radius, pixels at default zoom
         * 7. Orbit radius, pixels at default zoom
         * 8. Days it takes to complete an orbit. 1 day = 10 seconds.
         */

        // Salus Siphon Platform
        SectorEntityToken diktatsiphonStation = system.addCustomEntity("salus_siphon_plat", "Salus Siphon Platform", "station_side05", "sindrian_diktat");
        diktatsiphonStation.setInteractionImage("illustrations", "space_bar");
        diktatsiphonStation.setCircularOrbitPointingDown(system.getEntityById("salus"), 45, 400, 50);
        if (!isPAGSM) {
            diktatsiphonStation.setCustomDescriptionId("station_salus_siphon");
        }
        else {
            diktatsiphonStation.setCustomDescriptionId("station_salus_siphon_PAGSM");
        }

        // Opis Mining Platform
        SectorEntityToken diktatStation = system.addCustomEntity("opis_mining_plat", "Opis Mining Platform", "station_side00", "sindrian_diktat");
        diktatStation.setInteractionImage("illustrations", "industrial_megafacility");
        diktatStation.setCircularOrbitPointingDown(system.getEntityById("salus"), 45, 1100, 80);
        if (!isPAGSM) {
            diktatStation.setCustomDescriptionId("station_opis_mining");
        }
        else {
            diktatStation.setCustomDescriptionId("station_opis_mining_PAGSM");
        }

        // American fever dream
        if (!DEenablelitemode) {
            PlanetAPI drakon = system.addPlanet("drakon", system.getEntityById("askonia"), "Drakon", "frozen1", 280, 150, 12000, 1000);
            drakon.getSpec().setPitch(180f);
            drakon.getSpec().setTilt(-30f);
            drakon.getSpec().setGlowTexture(Global.getSettings().getSpriteName("hab_glows", "asharu"));
            drakon.applySpecChanges();
            drakon.setInteractionImage("illustrations", "cargo_loading");
            if (!isPAGSM) {
                drakon.setCustomDescriptionId("planet_drakon");
            } else {
                drakon.setCustomDescriptionId("planet_drakon_PAGSM");
            }
            if (!DEenablefortressmode) {
                MarketAPI drakon_market = addMarketplace(
                        "sindrian_diktat",
                        drakon,
                        null,
                        "Drakon",
                        4,

                        new ArrayList<>(
                                Arrays.asList(
                                        Conditions.POPULATION_4,
                                        Conditions.NO_ATMOSPHERE,
                                        Conditions.VERY_COLD,
                                        Conditions.DARK,
                                        Conditions.ORGANICS_PLENTIFUL,
                                        Conditions.VOLATILES_DIFFUSE,
                                        Conditions.OUTPOST,
                                        Conditions.FRONTIER
                                )
                        ),

                        new ArrayList<>(
                                Arrays.asList(
                                        Submarkets.SUBMARKET_OPEN,
                                        Submarkets.SUBMARKET_STORAGE,
                                        Submarkets.SUBMARKET_BLACK
                                )
                        ),
                        new ArrayList<>(
                                Arrays.asList(
                                        Industries.POPULATION,
                                        Industries.SPACEPORT,
                                        Industries.MINING,
                                        Industries.GROUNDDEFENSES
                                )
                        ),
                        //tariffs
                        0.3f,
                        //freeport
                        false,
                        //junk and chatter
                        true);
            }
            NascentGravityWellAPI well = Global.getSector().createNascentGravityWell(drakon, 50f);
            well.autoUpdateHyperLocationBasedOnInSystemEntityAtRadius(drakon, 470f);
            hyper.addEntity(well);

        // Ceyx 2.0 purple boogaloo
        PlanetAPI parthevia = system.addPlanet("parthevia", drakon, "Parthevia", "barren", 45, 40, 400, 60);
        parthevia.setCustomDescriptionId("planet_parthevia");
        parthevia.getMarket().addCondition(Conditions.VERY_COLD);
        parthevia.getMarket().addCondition(Conditions.NO_ATMOSPHERE);
        parthevia.getMarket().addCondition(Conditions.DARK);
        parthevia.getMarket().addCondition(Conditions.ORE_MODERATE);
        parthevia.getMarket().addCondition(Conditions.RARE_ORE_MODERATE);
        }

        // Drone command centre used to coordinate robot mining operations on Nortia - destroyed by Pathers long before Askonian Crisis
        SectorEntityToken neutralStation = system.addCustomEntity("nortia_abandoned_station", "Nortia Drone Command Hub", "station_side05", "neutral");
        neutralStation.setCircularOrbitPointingDown(system.getEntityById("nortia"), 45, 110, 100);
        neutralStation.setCustomDescriptionId("drone_hub");
        neutralStation.setInteractionImage("illustrations", "abandoned_station");

        Misc.setAbandonedStationMarket("nortia_abandoned_station_market", neutralStation);

        // Phrygian Immigration Checkpoint; border control for Askonia
        if (!DEenablelitemode) if (!DEenablefortressmode) {
            if (!isPAGSM) {
                SectorEntityToken phrygian = system.addCustomEntity("phrygian", "Phrygian Immigration Checkpoint", "station_side05", "sindrian_diktat");
                phrygian.setInteractionImage("illustrations", "orbital");
                phrygian.setCircularOrbitPointingDown(system.getEntityById("salus_jump"), 45, 400, 50);
                phrygian.setCustomDescriptionId("phrygian_immigration");
                MarketAPI phrygian_market = addMarketplace(
                        "sindrian_diktat",
                        phrygian,
                        null,
                        "Phrygian Immigration Checkpoint",
                        2,

                        new ArrayList<>(
                                Arrays.asList(
                                        Conditions.POPULATION_2,
                                        Conditions.NO_ATMOSPHERE,
                                        Conditions.OUTPOST
                                )
                        ),

                        new ArrayList<>(
                                Arrays.asList(
                                        Submarkets.SUBMARKET_OPEN,
                                        Submarkets.SUBMARKET_STORAGE,
                                        Submarkets.SUBMARKET_BLACK
                                )
                        ),
                        new ArrayList<>(
                                Arrays.asList(
                                        Industries.POPULATION,
                                        Industries.SPACEPORT,
                                        Industries.PATROLHQ,
                                        Industries.ORBITALSTATION,
                                        Industries.GROUNDDEFENSES
                                )
                        ),
                        //tariffs
                        0.3f,
                        //freeport
                        false,
                        //junk and chatter
                        true);
                phrygian.getMarket().setSurveyLevel(MarketAPI.SurveyLevel.FULL);
            } else {
                SectorEntityToken phrygian = system.addCustomEntity("phrygian_PAGSM", "Phrygian Customer Spotter", "station_side05", "sindrian_diktat");
                phrygian.setInteractionImage("illustrations", "orbital");
                phrygian.setCircularOrbitPointingDown(system.getEntityById("salus_jump"), 45, 400, 50);
                phrygian.setCustomDescriptionId("phrygian_immigration_PAGSM");
                MarketAPI phrygian_market = addMarketplace(
                        "sindrian_diktat",
                        phrygian,
                        null,
                        "Phrygian Customer Spotter",
                        2,

                        new ArrayList<>(
                                Arrays.asList(
                                        Conditions.POPULATION_2,
                                        Conditions.NO_ATMOSPHERE,
                                        Conditions.OUTPOST
                                )
                        ),

                        new ArrayList<>(
                                Arrays.asList(
                                        Submarkets.SUBMARKET_OPEN,
                                        Submarkets.SUBMARKET_STORAGE,
                                        Submarkets.SUBMARKET_BLACK
                                )
                        ),
                        new ArrayList<>(
                                Arrays.asList(
                                        Industries.POPULATION,
                                        Industries.SPACEPORT,
                                        Industries.PATROLHQ,
                                        Industries.ORBITALSTATION,
                                        Industries.GROUNDDEFENSES
                                )
                        ),
                        //tariffs
                        0.3f,
                        //freeport
                        false,
                        //junk and chatter
                        true);
                phrygian.getMarket().setSurveyLevel(MarketAPI.SurveyLevel.FULL);
            }
        } else {
            if (!isPAGSM) {
                SectorEntityToken phrygian = system.addCustomEntity("phrygian_fortress", "Phrygian Immigration Checkpoint", "station_side06", "sindrian_diktat");
                phrygian.setInteractionImage("illustrations", "orbital_construction");
                phrygian.setCircularOrbitPointingDown(system.getEntityById("salus_jump"), 45, 400, 50);
                phrygian.setCustomDescriptionId("phrygian_immigration_fortress");
                MarketAPI phrygian_market = addMarketplace(
                        "sindrian_diktat",
                        phrygian,
                        null,
                        "Phrygian Immigration Checkpoint",
                        4,

                        new ArrayList<>(
                                Arrays.asList(
                                        Conditions.POPULATION_4,
                                        Conditions.OUTPOST,
                                        Conditions.CLOSED_IMMIGRATION
                                )
                        ),

                        new ArrayList<>(
                                Arrays.asList(
                                        Submarkets.SUBMARKET_OPEN,
                                        Submarkets.GENERIC_MILITARY,
                                        Submarkets.SUBMARKET_STORAGE,
                                        Submarkets.SUBMARKET_BLACK
                                )
                        ),
                        new ArrayList<>(
                                Arrays.asList(
                                        Industries.POPULATION,
                                        Industries.SPACEPORT,
                                        Industries.HEAVYINDUSTRY,
                                        "lionsguard",
                                        Industries.MILITARYBASE,
                                        Industries.ORBITALSTATION,
                                        Industries.GROUNDDEFENSES
                                )
                        ),
                        //tariffs
                        0.3f,
                        //freeport
                        false,
                        //junk and chatter
                        true);
                phrygian.getMarket().setSurveyLevel(MarketAPI.SurveyLevel.FULL);
            } else {
                SectorEntityToken phrygian = system.addCustomEntity("phrygian_fortress_PAGSM", "Phrygian Customer Spotter & Academy", "station_side06", "sindrian_diktat");
                phrygian.setInteractionImage("illustrations", "orbital_construction");
                phrygian.setCircularOrbitPointingDown(system.getEntityById("salus_jump"), 45, 400, 50);
                phrygian.setCustomDescriptionId("phrygian_immigration_fortress_PAGSM");
                MarketAPI phrygian_market = addMarketplace(
                        "sindrian_diktat",
                        phrygian,
                        null,
                        "Phrygian Customer Spotter & Academy",
                        4,

                        new ArrayList<>(
                                Arrays.asList(
                                        Conditions.POPULATION_4,
                                        Conditions.OUTPOST,
                                        Conditions.CLOSED_IMMIGRATION
                                )
                        ),

                        new ArrayList<>(
                                Arrays.asList(
                                        Submarkets.SUBMARKET_OPEN,
                                        Submarkets.GENERIC_MILITARY,
                                        Submarkets.SUBMARKET_STORAGE,
                                        Submarkets.SUBMARKET_BLACK
                                )
                        ),
                        new ArrayList<>(
                                Arrays.asList(
                                        Industries.POPULATION,
                                        Industries.SPACEPORT,
                                        Industries.HEAVYINDUSTRY,
                                        "lionsguard",
                                        Industries.MILITARYBASE,
                                        Industries.ORBITALSTATION,
                                        Industries.GROUNDDEFENSES
                                )
                        ),
                        //tariffs
                        0.3f,
                        //freeport
                        false,
                        //junk and chatter
                        true);
                phrygian.getMarket().setSurveyLevel(MarketAPI.SurveyLevel.FULL);
            }
        }

    // Abiectis Military HQ - Askonia Ryzan Supercomplex analogue
    if (DEenablefortressmode) {
        if (!isPAGSM) {
            SectorEntityToken abiectis = system.addCustomEntity("abiectis_hq", "Abiectis Military Headquarters", "station_lowtech3", "sindrian_diktat");
            abiectis.setInteractionImage("illustrations", "orbital_construction");
            abiectis.setCircularOrbitPointingDown(system.getStar(), 240, 3600, 230);
            abiectis.setCustomDescriptionId("abiectis_hq");
            MarketAPI abiectis_market = addMarketplace(
                    "sindrian_diktat",
                    abiectis,
                    null,
                    "Abiectis Military Headquarters",
                    6,

                    new ArrayList<>(
                            Arrays.asList(
                                    Conditions.POPULATION_6,
                                    Conditions.NO_ATMOSPHERE,
                                    Conditions.HOT,
                                    Conditions.VOLATILES_ABUNDANT,
                                    Conditions.ORE_MODERATE,
                                    Conditions.RARE_ORE_MODERATE
                                    //Conditions.URBANIZED_POLITY
                            )
                    ),

                    new ArrayList<>(
                            Arrays.asList(
                                    Submarkets.SUBMARKET_OPEN,
                                    Submarkets.GENERIC_MILITARY,
                                    Submarkets.SUBMARKET_STORAGE,
                                    Submarkets.SUBMARKET_BLACK
                            )
                    ),
                    new ArrayList<>(
                            Arrays.asList(
                                    Industries.POPULATION,
                                    Industries.MEGAPORT,
                                    Industries.HEAVYBATTERIES,
                                    Industries.STARFORTRESS,
                                    Industries.WAYSTATION,
                                    Industries.MINING,
                                    Industries.REFINING,
                                    Industries.HIGHCOMMAND,
                                    Industries.FUELPROD
                            )
                    ),
                    //tariffs
                    0.3f,
                    //freeport
                    false,
                    //junk and chatter
                    true);
            if (!DEenablelitemode) {
                abiectis.getMarket().addCondition("DE_Patrioticfervor");
                abiectis.getMarket().getIndustry(Industries.REFINING).setSpecialItem(new SpecialItemData(Items.CATALYTIC_CORE, null));
            }
            abiectis.getMarket().getCondition(Conditions.VOLATILES_ABUNDANT).setSurveyed(true);
            abiectis.getMarket().getCondition(Conditions.ORE_MODERATE).setSurveyed(true);
            abiectis.getMarket().getCondition(Conditions.RARE_ORE_MODERATE).setSurveyed(true);
            abiectis.getMarket().setSurveyLevel(MarketAPI.SurveyLevel.FULL);
        } else {
            SectorEntityToken abiectis = system.addCustomEntity("abiectis_hq_PAGSM", "Abiectis Military Headquarters", "station_lowtech3", "sindrian_diktat");
            abiectis.setInteractionImage("illustrations", "orbital_construction");
            abiectis.setCircularOrbitPointingDown(system.getStar(), 240, 3600, 230);
            abiectis.setCustomDescriptionId("abiectis_hq_PAGSM");
            MarketAPI abiectis_market = addMarketplace(
                    "sindrian_diktat",
                    abiectis,
                    null,
                    "Abiectis Military Headquarters",
                    6,

                    new ArrayList<>(
                            Arrays.asList(
                                    Conditions.POPULATION_6,
                                    Conditions.NO_ATMOSPHERE,
                                    Conditions.HOT,
                                    Conditions.VOLATILES_ABUNDANT,
                                    Conditions.ORE_MODERATE,
                                    Conditions.RARE_ORE_MODERATE
                                    //Conditions.URBANIZED_POLITY
                            )
                    ),

                    new ArrayList<>(
                            Arrays.asList(
                                    Submarkets.SUBMARKET_OPEN,
                                    Submarkets.GENERIC_MILITARY,
                                    Submarkets.SUBMARKET_STORAGE,
                                    Submarkets.SUBMARKET_BLACK
                            )
                    ),
                    new ArrayList<>(
                            Arrays.asList(
                                    Industries.POPULATION,
                                    Industries.MEGAPORT,
                                    Industries.HEAVYBATTERIES,
                                    Industries.STARFORTRESS,
                                    Industries.WAYSTATION,
                                    Industries.MINING,
                                    Industries.REFINING,
                                    Industries.HIGHCOMMAND,
                                    Industries.FUELPROD
                            )
                    ),
                    //tariffs
                    0.3f,
                    //freeport
                    false,
                    //junk and chatter
                    true);
            if (!DEenablelitemode) {
                abiectis.getMarket().addCondition("DE_Patrioticfervor_PAGSM");
                abiectis.getMarket().getIndustry(Industries.REFINING).setSpecialItem(new SpecialItemData(Items.CATALYTIC_CORE, null));
                }
            abiectis.getMarket().getCondition(Conditions.VOLATILES_ABUNDANT).setSurveyed(true);
            abiectis.getMarket().getCondition(Conditions.ORE_MODERATE).setSurveyed(true);
            abiectis.getMarket().getCondition(Conditions.RARE_ORE_MODERATE).setSurveyed(true);
            abiectis.getMarket().setSurveyLevel(MarketAPI.SurveyLevel.FULL);
            }
        }
    }
}






